### ISSUE TITLE
Problems setting up project

### ISSUE THREAD

**Issue by gabrielsaldana** [ohsu-computational-biology/server#16]
I'm trying to set up a development environment with Docker following the current documentation at http://ga4gh-reference-implementation.readthedocs.org/en/latest/installation.html#deployment-on-docker  but ran into some issues:
1. After docker image build, running: docker run myimage Outputs an error: OSError: [Errno 2] No such file or directory: '/ga4gh-example-data/referenceSets'
2. The link for the example data at http://www.well.ox.ac.uk/~jk/ga4gh-example-data.tar.gz is broken
3. After trying another command: docker run -d -p 8000:80 --name ga4gh_demo afirth/ga4gh-server:develop-demo  Got error: Error pulling image (develop-demo) from docker.io/afirth/ga4gh-server, Untar re-exec error: exit status 1: output: write /data/ga4gh-example-data/reads/low-coverage/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam: no space left on device

Am I missing something from the documentation or does the docs need more details or an update?

**Comment by bwalsh** [comment]
Thanks Gabriel.   Can you enter this in the https://github.com/ga4gh/server repo?
Much appreciated
