### ISSUE TITLE
uncomment debug flag, exercise git workflow

### ISSUE THREAD

**Issue by bwalsh** [ohsu-computational-biology/server#2]
See https://github.com/ga4gh/server/pull/607#issuecomment-138968395

In order to have a simple dry run of our git workflow, I thought it would be good to exercise it with a simple 1 line change, please:
- fork this repo https://github.com/ohsu-computational-biology/server
- uncomment bug tests/unit/test_views.py
- run tests, ensure they pass
- create pull request

**Comment by bwalsh** [comment]
Also, there is a second one line change

https://github.com/ga4gh/server/pull/607#issuecomment-138990818

**Comment by adamstruck** [comment]
I finished this exercise.
