### ISSUE TITLE
client code

### ISSUE THREAD

**Issue by bwalsh** [ohsu-computational-biology/server#5]
See
https://github.com/ga4gh/server/pull/607#issuecomment-139208912

```
Client code

There is no client API provided. This should be added and tested, so we can run queries from the command line without using curl or whatever.
```
## use case

`As a researcher, in order to use the G2P api in a python notebook, I need a  client side api to integrate it.`

---

**Please read the code and create a design on how a client api might be used.**

See

https://github.com/ohsu-computational-biology/server/blob/develop/ga4gh/client.py
https://github.com/ohsu-computational-biology/server/blob/develop/tests/unit/test_client.py

**Comment by adamstruck** [comment]
Issue closed. See pull request #6
